node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
 /* stage('SonarQube analysis') {
        script {
            scannerHome = tool 'sonarqube';
        }
        withSonarQubeEnv('sonarqube') {
            sh """
            sonar-scanner \
  -Dsonar.projectKey=jenkins \
  -Dsonar.sources=. \
  -Dsonar.host.url=http://192.168.100.18:9000 \
  -Dsonar.login=fc10e93d7010fb7107635563ec693c0a96eb38eb
        """
        }
    } */
   /*stage('sonar-scanner') {
      def sonarqubeScannerHome = tool name: 'sonarqube', type: 'hudson.plugins.sonar.SonarRunnerInstallation'
      withCredentials([string(credentialsId: 'sonarqube', variable: 'sonarLogin')]) {
        sh "${sonarqubeScannerHome}/bin/sonar-scanner -e -Dsonar.host.url=http://192.168.100.20:9000 -Dsonar.login=52ee6a34b6c78beee00ce12cbd4ae6a449f4bb93 -Dsonar.projectName=jenkins -Dsonar.projectVersion=${env.BUILD_NUMBER} -Dsonar.projectKey=jenkins -Dsonar.language=java -Dsonar.java.binaries=."
      }
    }*/
  
   /*stage('Initialize'){
        def dockerHome = tool 'docker'
        env.PATH = "${dockerHome}/bin:${env.PATH}"
    }*/
   
   stage('docker build/push') {
       def app = docker.build("ce318002/jenkins-docker:${commit_id}", '.')
   }
}
